print(' welcome to the wprld of mad libs by DIVAX SHAH ')
print(' THE GAME BASED ON FULL OF TEXT BASED THINGS')
print('***** I WILL ASK FOR SOME INPUTS PLEASE ENTER IT :) *****')
noun1=input("input a noun : ")
vi=input("input a verb ending with ing : ")
noun2=input("input a noun again : ")
exc=input("an exclamation : ")
vi2=input("an verb ending with ing : ")
np=input("an plural noun : ")
n3=input("an noun :  ")
vpt=input("an verb in past tense : ")
n4=input("an noun : ")
adj=input("and adjective : ")
print()
print()
print('  PUT YOUR HANDS UP said the '+noun1+" you are under arrest for "+vi+" the "+noun2+" at the "+exc+"! .",end="")
print("though you. his hands were "+vi2+" like "+np+" on a "+n3+" . this was not the first time he had "+vpt+" a "+n4+" and he knew he was in "+adj+" trouble.")

xxx=input()

